import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ApiError } from "../api/client";
import { enquiryApi, quotationApi } from "../api/resources";
import { ErrorNotice, EmptyState, Field, LoadingState, PageHeader, StatusBadge, SuccessNotice } from "../components/ui";
import type { EnquiryDetail, Quotation } from "../types";

type QuoteLine = { productId: string; productName: string; quantity: string; unitPrice: string; discountPercent: string; gstPercent: string };
const money = (value: number) => value.toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });

export const Quotations = () => {
  const navigate = useNavigate();
  const [quotations, setQuotations] = useState<Quotation[]>([]);
  const [enquiries, setEnquiries] = useState<EnquiryDetail[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [showForm, setShowForm] = useState(false); const [selectedEnquiry, setSelectedEnquiry] = useState(""); const [validUntil, setValidUntil] = useState(""); const [lines, setLines] = useState<QuoteLine[]>([]);
  const load = async () => { setLoading(true); setError(""); try { const [quoteData, enquiryData] = await Promise.all([quotationApi.list(), enquiryApi.list()]); setQuotations(quoteData.quotations); setEnquiries(enquiryData.enquiries); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to load quotations. Please try again."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const chooseEnquiry = (id: string) => { setSelectedEnquiry(id); const detail = enquiries.find((entry) => entry.enquiry.id === id); setLines(detail?.items.map((item) => ({ productId: item.productId, productName: item.productName, quantity: item.quantity, unitPrice: "", discountPercent: "0", gstPercent: "18" })) ?? []); };
  const updateLine = (index: number, key: keyof QuoteLine, value: string) => setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, [key]: value } : line));
  const totals = lines.reduce((result, line) => { const base = Number(line.quantity) * Number(line.unitPrice); const discount = base * Number(line.discountPercent) / 100; const gst = (base - discount) * Number(line.gstPercent) / 100; result.subtotal += base; result.discount += discount; result.gst += gst; result.grand += base - discount + gst; return result; }, { subtotal: 0, discount: 0, gst: 0, grand: 0 });
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { await quotationApi.create({ enquiryId: selectedEnquiry, validUntil, items: lines.map(({ productId, quantity, unitPrice, discountPercent, gstPercent }) => ({ productId, quantity, unitPrice, discountPercent, gstPercent })) }); setSuccess("Quotation created as DRAFT."); setShowForm(false); setSelectedEnquiry(""); setLines([]); await load(); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to create quotation."); } finally { setSaving(false); } };
  const transition = async (quotation: Quotation, status: "SENT" | "ACCEPTED" | "REJECTED") => { setSaving(true); setError(""); try { await quotationApi.updateStatus(quotation.id, status); setSuccess(`Quotation moved to ${status}.`); await load(); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to update quotation status."); } finally { setSaving(false); } };
  const convert = async (quotation: Quotation) => { setSaving(true); setError(""); try { await quotationApi.convert(quotation.id); navigate("/sales-orders"); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to convert quotation."); } finally { setSaving(false); } };
  return <section className="page"><PageHeader eyebrow="Pipeline / 02" title="Quotations" description="Turn qualified demand into a clear commercial offer." action={<button className="button button-primary" onClick={() => setShowForm(true)}>New quotation <span>＋</span></button>} />{error && <ErrorNotice message={error} />}{success && <SuccessNotice message={success} />}
    {showForm && <div className="form-panel"><div className="panel-heading"><div><span className="eyebrow">Commercial offer</span><h2>Create a quotation</h2></div><button className="icon-button" onClick={() => setShowForm(false)} aria-label="Close form">×</button></div><form onSubmit={submit}><div className="form-grid"><Field label="Source enquiry" required><select value={selectedEnquiry} onChange={(e) => chooseEnquiry(e.target.value)} required><option value="">Select enquiry</option>{enquiries.filter((entry) => !["WON", "LOST"].includes(entry.enquiry.status)).map((entry) => <option key={entry.enquiry.id} value={entry.enquiry.id}>{entry.enquiry.enquiryNumber} · {entry.enquiry.items?.length ?? 0} products</option>)}</select></Field><Field label="Valid until" required><input type="date" value={validUntil} onChange={(e) => setValidUntil(e.target.value)} required /></Field></div>{selectedEnquiry && <div className="line-items quote-lines">{lines.map((line, index) => <div className="quote-line" key={line.productId}><div><strong>{line.productName}</strong><small>Qty {line.quantity}</small></div><input aria-label={`${line.productName} unit price`} type="number" min="0" step="0.01" placeholder="Unit price" value={line.unitPrice} onChange={(e) => updateLine(index, "unitPrice", e.target.value)} required /><input aria-label={`${line.productName} discount`} type="number" min="0" max="100" step="0.01" placeholder="Discount %" value={line.discountPercent} onChange={(e) => updateLine(index, "discountPercent", e.target.value)} required /><input aria-label={`${line.productName} GST`} type="number" min="0" max="100" step="0.01" placeholder="GST %" value={line.gstPercent} onChange={(e) => updateLine(index, "gstPercent", e.target.value)} required /></div>)}</div>}{selectedEnquiry && <div className="totals"><div><span>Subtotal</span><strong>{money(totals.subtotal)}</strong></div><div><span>Discount</span><strong>- {money(totals.discount)}</strong></div><div><span>GST</span><strong>{money(totals.gst)}</strong></div><div className="grand-total"><span>Estimated grand total</span><strong>{money(totals.grand)}</strong></div></div>}<div className="form-actions"><button type="button" className="button button-secondary" onClick={() => setShowForm(false)}>Cancel</button><button className="button button-primary" disabled={saving || !selectedEnquiry}>{saving ? "Creating..." : "Create draft"}</button></div></form></div>}
    <div className="table-card">{loading ? <LoadingState label="Loading quotations..." /> : quotations.length === 0 ? <EmptyState title="No quotations found." /> : <div className="table-scroll"><table><thead><tr><th>Quotation</th><th>Customer</th><th>Enquiry</th><th>Valid until</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{quotations.map((quotation) => <tr key={quotation.id}><td><strong>{quotation.quotationNumber}</strong><small>{quotation.items.length} line items</small></td><td>{quotation.customer?.companyName ?? "—"}</td><td>{quotation.enquiry?.enquiryNumber ?? "—"}</td><td>{quotation.validUntil}</td><td><strong>{money(Number(quotation.grandTotal))}</strong></td><td><StatusBadge status={quotation.status} /></td><td><div className="row-actions">{quotation.status === "DRAFT" && <button className="button button-small" disabled={saving} onClick={() => transition(quotation, "SENT")}>Send</button>}{quotation.status === "SENT" && <><button className="button button-small button-primary" disabled={saving} onClick={() => transition(quotation, "ACCEPTED")}>Accept</button><button className="button button-small" disabled={saving} onClick={() => transition(quotation, "REJECTED")}>Reject</button></>}{quotation.status === "ACCEPTED" && <button className="button button-small button-primary" disabled={saving} onClick={() => convert(quotation)}>Convert to order</button>}</div></td></tr>)}</tbody></table></div>}</div>
  </section>;
};
