import { Fragment, useEffect, useState } from "react";
import { ApiError } from "../api/client";
import { inventoryApi, salesOrderApi } from "../api/resources";
import { ErrorNotice, EmptyState, Field, LoadingState, PageHeader, StatusBadge, SuccessNotice } from "../components/ui";
import { useAuth } from "../context/AuthContext";
import type { InventoryRow, SalesOrder } from "../types";

const money = (value: string) => Number(value).toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });
export const SalesOrders = () => {
  const { user } = useAuth(); const [orders, setOrders] = useState<SalesOrder[]>([]); const [inventory, setInventory] = useState<InventoryRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [dispatchOrder, setDispatchOrder] = useState<SalesOrder | null>(null); const [vehicleNumber, setVehicleNumber] = useState(""); const [driverName, setDriverName] = useState(""); const [saving, setSaving] = useState(false); const [expanded, setExpanded] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(""); try { const [orderData, inventoryData] = await Promise.all([salesOrderApi.list(), inventoryApi.list()]); setOrders(orderData.salesOrders); setInventory(inventoryData.inventory); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to load Sales Orders. Please try again."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const confirm = async (order: SalesOrder) => { setSaving(true); setError(""); try { await salesOrderApi.confirm(order.id); setSuccess(`${order.salesOrderNumber} confirmed and inventory reserved.`); await load(); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to confirm Sales Order."); } finally { setSaving(false); } };
  const dispatch = async (event: React.FormEvent) => { event.preventDefault(); if (!dispatchOrder) return; setSaving(true); setError(""); try { await salesOrderApi.dispatch(dispatchOrder.id, { vehicleNumber, driverName }); setSuccess(`${dispatchOrder.salesOrderNumber} dispatched successfully.`); setDispatchOrder(null); setVehicleNumber(""); setDriverName(""); await load(); } catch (err) { setError(err instanceof ApiError ? err.message : "Unable to dispatch Sales Order."); } finally { setSaving(false); } };
  return <section className="page"><PageHeader eyebrow="Fulfilment / 03" title="Sales Orders" description="Track commitments from confirmation through dispatch." />{error && <ErrorNotice message={error} />}{success && <SuccessNotice message={success} />}
    {dispatchOrder && <div className="form-panel compact-panel"><div className="panel-heading"><div><span className="eyebrow">Final mile</span><h2>Dispatch {dispatchOrder.salesOrderNumber}</h2></div><button className="icon-button" onClick={() => setDispatchOrder(null)} aria-label="Close form">×</button></div><form onSubmit={dispatch}><div className="form-grid"><Field label="Vehicle number" required><input value={vehicleNumber} onChange={(e) => setVehicleNumber(e.target.value)} placeholder="MH-12-AB-1234" required /></Field><Field label="Driver name" required><input value={driverName} onChange={(e) => setDriverName(e.target.value)} placeholder="Driver name" required /></Field></div><div className="form-actions"><button type="button" className="button button-secondary" onClick={() => setDispatchOrder(null)}>Cancel</button><button className="button button-primary" disabled={saving}>{saving ? "Dispatching..." : "Dispatch order"}</button></div></form></div>}
    <div className="table-card">{loading ? <LoadingState label="Loading Sales Orders..." /> : orders.length === 0 ? <EmptyState title="No Sales Orders found." /> : <div className="table-scroll"><table><thead><tr><th>Order</th><th>Customer</th><th>Quotation</th><th>Order date</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map((order) => <Fragment key={order.id}><tr><td><button className="table-link" onClick={() => setExpanded(expanded === order.id ? null : order.id)}><strong>{order.salesOrderNumber}</strong><small>{order.items.length} line items</small></button></td><td>{order.customer?.companyName ?? "—"}</td><td>{order.quotation?.quotationNumber ?? "—"}</td><td>{order.orderDate}</td><td><strong>{money(order.totalAmount)}</strong></td><td><StatusBadge status={order.status} /></td><td>{user?.role === "ADMIN" && order.status === "PENDING" && <button className="button button-small button-primary" disabled={saving} onClick={() => confirm(order)}>Confirm order</button>}{user?.role === "ADMIN" && order.status === "CONFIRMED" && <button className="button button-small button-primary" disabled={saving} onClick={() => setDispatchOrder(order)}>Dispatch order</button>}{order.status === "DISPATCHED" && <span className="muted">Complete</span>}</td></tr>{expanded === order.id && <tr className="detail-row"><td colSpan={7}><div className="order-detail"><div className="detail-summary"><span>Source enquiry <strong>{order.enquiry?.enquiryNumber ?? "—"}</strong></span><span>Availability <strong>{order.status === "PENDING" ? "Not reserved" : "Reserved / fulfilled"}</strong></span></div><div className="mini-table"><div className="mini-head"><span>Product</span><span>Qty</span><span>Unit price</span><span>Discount</span><span>GST</span><span>Line total</span></div>{order.items.map((item) => <div className="mini-row" key={item.id}><span>{item.productName}</span><span>{item.quantity}</span><span>{money(item.unitPrice)}</span><span>{item.discountPercent}%</span><span>{item.gstPercent}%</span><span>{money(item.lineAmount)}</span></div>)}</div></div></td></tr>}</Fragment>)}</tbody></table></div>}</div>
    <div className="availability-strip"><div><span className="eyebrow">Inventory pulse</span><h2>Availability at a glance</h2></div><div className="availability-list">{inventory.slice(0, 4).map((row) => <div className="availability-item" key={row.product.id}><span>{row.product.productName}</span><strong>{row.availableQuantity}</strong><small>available</small></div>)}</div></div>
  </section>;
};
